version: '3.4'

services:
  catalogdb:
    image: mongo

  basketdb:
    image: redis:alpine

  discountdb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce

  catalog.service:
    image: ${DOCKER_REGISTRY-}catalogservice
    build:
      context: .
      dockerfile: Services/CatalogService/Catalog.Service/Dockerfile

  basket.service:
    image: ${DOCKER_REGISTRY-}basketservice
    build:
      context: .
      dockerfile: Services/BasketService/Basket.Service/Dockerfile

  discount.service:
    image: ${DOCKER_REGISTRY-}discountservice
    build:
      context: .
      dockerfile: Services/DiscountService/Discount.Service/Dockerfile

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:

