version: '3.4'

services:
  catalogdb:
    image: mongo

  basketdb:
    image: redis:alpine

  discountdb:
    image: postgres

  orderdb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  pgadmin:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce

  catalog.service:
    image: ${DOCKER_REGISTRY-}catalogservice
    build:
      context: .
      dockerfile: Services/CatalogService/Catalog.Service/Dockerfile

  basket.service:
    image: ${DOCKER_REGISTRY-}basketservice
    build:
      context: .
      dockerfile: Services/BasketService/Basket.Service/Dockerfile

  discount.service:
    image: ${DOCKER_REGISTRY-}discountservice
    build:
      context: .
      dockerfile: Services/DiscountService/Discount.Service/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/DiscountService/Discount.Grpc/Dockerfile

  ordering.service:
    image: ${DOCKER_REGISTRY-}orderingservice
    build:
      context: .
      dockerfile: Services/OrderingService/Ordering.Service/Dockerfile

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:



